package tugasBesar2;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class GajiKaryawan extends javax.swing.JFrame {
    
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();

    /**
     * Creates new form GajiKaryawan
     */
    public GajiKaryawan() {
        initComponents();
        k.connect();
        refreshTable();
    }
    
    class gaji extends GajiKaryawan {
        int nik, gaji_pokok;
        String nama_lengkap, jabatan;

        public gaji() {
            this.nama_lengkap = txtNamaGaji.getText();
            this.jabatan = txtJabatanGaji.getText();
            this.gaji_pokok = Integer.parseInt(txtGajiPokok.getText());
        }
    }
    
    public void refreshTable() {
        model = new DefaultTableModel();
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Jabatan");
        model.addColumn("Gaji Pokok");
        tabelGajiKaryawan.setModel(model);
        
        try {
            this.stat = k.getCon().prepareStatement("SELECT * FROM karyawan");
            this.rs = this.stat.executeQuery();
            while(rs.next()){
                Object[] data = {
                    rs.getInt("nik"),
                    rs.getString("nama_lengkap"),
                    rs.getString("jabatan"),
                    rs.getInt("gaji_pokok"),
                };
                model.addRow(data);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void kosongkanForm(){
        txtNIKGaji.setText(null);
        txtNamaGaji.setText(null);
        txtJabatanGaji.setText(null);
        txtGajiPokok.setText(null);
        txtTransportasi.setText(null);
        txtTunjangan.setText(null);
        slipGaji.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNIKGaji = new javax.swing.JTextField();
        txtGajiPokok = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtJabatanGaji = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNamaGaji = new javax.swing.JTextField();
        tbHapusGaji = new javax.swing.JButton();
        tbHitungGaji = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTransportasi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTunjangan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelGajiKaryawan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tbKeluar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        slipGaji = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Nama Karyawan");

        jLabel8.setText("NIK");

        txtNIKGaji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNIKGaji.setEnabled(false);
        txtNIKGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIKGajiActionPerformed(evt);
            }
        });

        txtGajiPokok.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtGajiPokok.setEnabled(false);
        txtGajiPokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGajiPokokActionPerformed(evt);
            }
        });

        jLabel9.setText("Gaji Pokok");

        txtJabatanGaji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtJabatanGaji.setEnabled(false);
        txtJabatanGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJabatanGajiActionPerformed(evt);
            }
        });

        jLabel4.setText("Jabatan");

        txtNamaGaji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNamaGaji.setEnabled(false);
        txtNamaGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaGajiActionPerformed(evt);
            }
        });

        tbHapusGaji.setText("Hapus");
        tbHapusGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusGajiActionPerformed(evt);
            }
        });

        tbHitungGaji.setText("Hitung");
        tbHitungGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHitungGajiActionPerformed(evt);
            }
        });

        jLabel10.setText("Transportasi");

        txtTransportasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTransportasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransportasiActionPerformed(evt);
            }
        });

        jLabel11.setText("Tunjangan");

        txtTunjangan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTunjangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTunjanganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(239, 239, 239))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamaGaji)
                                    .addComponent(txtJabatanGaji)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNIKGaji)
                                    .addComponent(txtGajiPokok)
                                    .addComponent(txtTransportasi)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(37, 37, 37)
                                .addComponent(txtTunjangan)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbHitungGaji)
                .addGap(18, 18, 18)
                .addComponent(tbHapusGaji)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNIKGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJabatanGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTransportasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbHitungGaji)
                    .addComponent(tbHapusGaji))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        tabelGajiKaryawan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelGajiKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIK", "Nama", "Jabatan", "Gaji Pokok"
            }
        ));
        tabelGajiKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelGajiKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelGajiKaryawan);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("GAJI KARYAWAN");

        tbKeluar.setText("X");
        tbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKeluarActionPerformed(evt);
            }
        });

        slipGaji.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        slipGaji.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jScrollPane3.setViewportView(slipGaji);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tbKeluar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbKeluar)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGajiPokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGajiPokokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGajiPokokActionPerformed

    private void txtNamaGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaGajiActionPerformed

    private void txtJabatanGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJabatanGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJabatanGajiActionPerformed

    private void tbHapusGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusGajiActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_tbHapusGajiActionPerformed

    private void tbHitungGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHitungGajiActionPerformed
        // TODO add your handling code here:
        int gajiPokok = Integer.parseInt(txtGajiPokok.getText());
        int transport = Integer.parseInt(txtTransportasi.getText());
        int tunjangan = Integer.parseInt(txtTunjangan.getText());
        
        String nama = txtNamaGaji.getText();
        String jabatan = txtJabatanGaji.getText();
        String nik = txtNIKGaji.getText();
        
        int totalGaji = gajiPokok + transport + tunjangan;
        
        slipGaji.setText("  =================\n" +
                "            Slip Gaji\n" +
                "  --------------------------------\n" +
                "  NIK\t : " + nik + "\n" +
                "  Nama\t : " + nama + "\n" +
                "  Jabatan\t : " + jabatan + "\n" +
                "  --------------------------------\n" +
                "  Gaji\t : Rp. " + totalGaji + "\n" +
                "  =================");
        
        
        
//        String slipGajiText = 
//                "=================\n" +
//                "          Slip Gaji\n" +
//                "--------------------------------\n" +
//                "NIK\t : " + nik + "\n" +
//                "Nama\t : " + nama + "\n" +
//                "Jabatan\t : " + jabatan + "\n" +
//                "--------------------------------\n" +
//                "Total Gaji\t : Rp. " + totalGaji + "\n" +
//                "=================";
//        JOptionPane.showMessageDialog(null, slipGajiText, "Slip Gaji", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_tbHitungGajiActionPerformed

    private void tabelGajiKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelGajiKaryawanMouseClicked
        // TODO add your handling code here:
        txtNIKGaji.setText(model.getValueAt(tabelGajiKaryawan.getSelectedRow(), 0).toString());
        txtNamaGaji.setText(model.getValueAt(tabelGajiKaryawan.getSelectedRow(),1).toString());
        txtJabatanGaji.setText(model.getValueAt(tabelGajiKaryawan.getSelectedRow(),2).toString());
        txtGajiPokok.setText(model.getValueAt(tabelGajiKaryawan.getSelectedRow(),3).toString());
    }//GEN-LAST:event_tabelGajiKaryawanMouseClicked

    private void txtNIKGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIKGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIKGajiActionPerformed

    private void txtTransportasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransportasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransportasiActionPerformed

    private void txtTunjanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTunjanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTunjanganActionPerformed

    private void tbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKeluarActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tbKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GajiKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane slipGaji;
    private javax.swing.JTable tabelGajiKaryawan;
    private javax.swing.JButton tbHapusGaji;
    private javax.swing.JButton tbHitungGaji;
    private javax.swing.JButton tbKeluar;
    private javax.swing.JTextField txtGajiPokok;
    private javax.swing.JTextField txtJabatanGaji;
    private javax.swing.JTextField txtNIKGaji;
    private javax.swing.JTextField txtNamaGaji;
    private javax.swing.JTextField txtTransportasi;
    private javax.swing.JTextField txtTunjangan;
    // End of variables declaration//GEN-END:variables
}
